title: Hoonio
email:
description: >
  Bridging the gap between ideas and technology
url: "https://www.hoonio.com"
twitter_username: hoonio
github_username:  hoonio
logo: "/assets/images/logo.png"

repository: "hoonio/hoonio.github.io"

minimal_mistakes_skin: dark
search: true
atom_feed:
  hide: true

# Build settings
# markdown: kramdown
theme: minimal-mistakes-jekyll
# remote_theme: mmistakes/minimal-mistakes
# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

# Plugins (previously gems:)
plugins:
  - jekyll-environment-variables
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-gist
  - jemoji

author:
  name   : "Hoonio"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Engineer by trade, Stoic, Fiddler & Wanderer"
  links:
    - label: instagram
      icon: "fab fa-fw fa-instagram"
      url: https://hoon.io/1wGEoKi

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/hoonio"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hoonio"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: https://hoon.io/link2in
    - label: youtube
      icon: "fab fa-fw fa-youtube"
      url: https://hoon.io/link2yt

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      # author_profile: true
      # read_time: true
      # comments: true
      # share: true
      # related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      # author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
