title: Hoonio
email: ""
description: >
  Root relaunch with Jekyll and Github Pages
url: "https://hoonio.com"
twitter_username: hoonio
github_username:  hoonio

repository: "hoonio/hoonio.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - index.md
  - blog/index.md
  - profile/index.md
  - contact/index.md

social_links:
  - name: facebook
    url: https://hoon.io/link2fb
  - name: instagram
    url: https://hoon.io/1wGEoKi
  - name: youtube
    url: https://hoon.io/link2yt

footer_links:
  - name: Dory
    url: https://dory.hoonio.com
  - name: Feria
    url: https://feria.hoonio.com
  - name: Wiki
    url: http://wiki.hoonio.com

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
