name: Workflow

on:
  push:
    paths-ignore:
    - 'package.json'

jobs:
  version:
    name: Bump Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.version }}
      release: ${{ steps.semver.outputs.patch }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: paulhatch/semantic-version@v4.0.2
      id: semver
      with:
        bump_each_commit: true

  build:
    name: Build with Jekyll
    needs: version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems- 
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Build with Jekyll
      id: commit
      run: |
        gem install jekyll bundler
        bundle install
        jekyll build --verbose
      env:
        JEKYLL_ENV: production
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        VERSION: ${{ needs.version.outputs.version }}
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v0

  report:
    name: Report Build Status
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Report Build Status
      uses: actions/deploy-pages@v1
      with:
        emit_telemetry: true

  publish:
    name: Publish to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
    - name: Delete artifact
      if: always()
      uses: geekyeggo/delete-artifact@v1
      with:
        name: github-pages

  tag-version:
    name: Release version
    needs: [ version, publish ]
    runs-on: ubuntu-latest
    if: needs.version.outputs.release == 0
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Tag version in repository
      run: |
        git config user.email "ci@hoonio.com"
        git config user.name "Hoonio"
        npm version ${{ needs.version.outputs.version }}
        git push origin master
        git push origin v${{ needs.version.outputs.version }}
